# Generated by Django 3.0.7 on 2020-07-07 23:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CmccDemo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.FileField(upload_to='images/')),
                ('summary', models.CharField(max_length=200)),
                ('new_field', models.CharField(default='Subtopic', max_length=200)),
                ('blog_content', models.TextField()),
            ],
        ),
    ]
