# Generated by Django 3.0.7 on 2020-07-07 23:36

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('cmccDemos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cmccdemo',
            name='create_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
