# Generated by Django 3.0.3 on 2020-02-28 00:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cmccDemos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cmccdemo',
            name='image',
            field=models.ImageField(upload_to='images/'),
        ),
    ]
