# Generated by Django 3.0.3 on 2020-03-12 00:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cmccDemos', '0002_auto_20200228_0053'),
    ]

    operations = [
        migrations.AddField(
            model_name='cmccdemo',
            name='new_field',
            field=models.CharField(default='SOME STRING', max_length=140),
        ),
        migrations.AlterField(
            model_name='cmccdemo',
            name='image',
            field=models.FileField(upload_to='images/'),
        ),
    ]
