# Generated by Django 3.0.7 on 2020-07-05 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cmccDemos', '0005_auto_20200705_2057'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cmccdemo',
            old_name='topic',
            new_name='summary',
        ),
        migrations.RemoveField(
            model_name='cmccdemo',
            name='blog_content',
        ),
        migrations.RemoveField(
            model_name='cmccdemo',
            name='create_date',
        ),
        migrations.RemoveField(
            model_name='cmccdemo',
            name='subtopic',
        ),
        migrations.AddField(
            model_name='cmccdemo',
            name='new_field',
            field=models.CharField(default='SOME STRING', max_length=5000),
        ),
    ]
